config/routes.rb
Rails.application.routes.draw do
	get 'todos', to:'todos#index'
	get 'todos/new'
	post 'todos', to:'todos#create'
	get 'todos/:id', to:'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as:'edit'
  patch 'todos/:id', to: 'todos#update'
 	delete 'todos/:id', to: 'todos#destroy'
 	get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
 	get 'todo/list', to: 'todos#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validates :description, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController	
	def index
		@todos = Todo.all
	end

	def new
		@todos = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
 	end

 	def update
 	 @todo = Todo.find(params[:id])	
	 @todo.update(todo_params)
	 redirect_to todos_path
 	end

 	def destroy
 		@todo = Todo.find(params[:id])
 		@todo.destroy
 		redirect_to todos_path
 	end

 	def complete
 		@todo = Todo.find(params[:id])
 		@todo.completed = true
 		@todo.save
 		redirect_to todos_path
 	end

 	def list
 		@todos = Todo.all
 		@completados = Todo.where(completed: true)
 		@no_completados = Todo.where(completed: false)
 	end

	private
		def todo_params
			params.require(:todo).permit(:description, :completed)
		end

		def find_todo
			@todo = Todo.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= todos_path %>">Index</a></li>
        <li><a href="<%= todos_new_path %>">New Todo</a></li>
        <li><a href="<%= todo_list_path %>">List</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<%= form_with(model: @todo, local: true) do |f| %>
 <%= f.label :description, "Description" %>
 <%= f.text_field :description %>
 <%= f.label :completed, "Completed" %>
 <%= f.text_field :completed %>
 <%= f.submit :crear %>
<% end %>

app/views/todos/index.html.erb
<div class="well">
	<table class="table">
    
	<th>DESCRIPTION</th>
    <th>COMPLETED</th>

	<% @todos.each do |todo| %>
	<tr>
		 <td><%= todo.description %></td>
		 <td><%= todo.completed %></td>
		 <td><%= link_to "Mostrar", todo, class: "btn btn-primary" %></td>
		 <td><%= link_to "Editar", edit_path(todo), class: "btn btn-info" %></td>
		 <td><%= link_to "Complete", complete_path(todo), class: "btn btn-success" %></td>
		 <td><%= link_to "Borrar", todo, method: :delete, data: { confirm: 'Estas Seguro?' }, class: "btn btn-danger"  %></td>
	</tr>
	<% end %>
	</table>
	<%= link_to "Crear", todos_new_path, class: "btn btn-primary btn-block" %>
</div>

                

app/views/todos/list.html.erb
<div class="row">
  <div class="col-md-6">
  	<h2>COMPLETADOS</h2>
  	  <table class="table table-sm">
			<tr>
		    <th>Description</th>
		    <th>Completed</br></th>
		  </tr >
  	<% @completados.each do |notodo| %>
  	<tr>
		 <td><%= notodo.description %></td>
		 <td><%= notodo.completed %></td>
		 </tr >
		
	<% end %>
	</table>
  </div>
    <div class="col-md-6">
  	<h2> NO COMPLETADOS</h2>
  	  <table class="table table-sm">
			<tr>
		    <th>Description</th>
		    <th>Completed</br></th>
		  </tr >
  	<% @no_completados.each do |todo| %>
  	<tr>
		 <td><%= todo.description %></td>
		 <td><%= todo.completed %></td>
		 </tr >
		
	<% end %>
	</table>
  </div>
</div>

app/views/todos/new.html.erb
<%= form_with(model: @todos, local: true) do |f| %>
 <%= f.label :description, "Description" %>
 <%= f.text_field :description %>
 <%= f.label :completed, "Completed" %>
 <%= f.text_field :completed %>
 <%= f.submit :crear %>
<% end %>

app/views/todos/show.html.erb
<h1><%= @todo.description %></h1>
<p><%= @todo.completed %></p>
<p><%= time_ago_in_words @todo.created_at %></p>
<%= link_to "ToDo", todos_path %>